// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6BKs_ncMjV1gWj-ysbYMxrK__MjWYO2o',
    appId: '1:381630717842:web:b14a2ebb98d279e8b66b4b',
    messagingSenderId: '381630717842',
    projectId: 'savorsip-8c64d',
    authDomain: 'savorsip-8c64d.firebaseapp.com',
    storageBucket: 'savorsip-8c64d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8j1vb3-Gl-6ncsO-x4DV7bQEMVkhLWE',
    appId: '1:381630717842:android:91e0383bd3ed6d8cb66b4b',
    messagingSenderId: '381630717842',
    projectId: 'savorsip-8c64d',
    storageBucket: 'savorsip-8c64d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZXHyXeB-ND8m4l_4ZS2p0svuhzhUBuqM',
    appId: '1:381630717842:ios:ce5e62771ae6a16fb66b4b',
    messagingSenderId: '381630717842',
    projectId: 'savorsip-8c64d',
    storageBucket: 'savorsip-8c64d.appspot.com',
    iosBundleId: 'com.example.savorsip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZXHyXeB-ND8m4l_4ZS2p0svuhzhUBuqM',
    appId: '1:381630717842:ios:5ec5bf8b35e45ef3b66b4b',
    messagingSenderId: '381630717842',
    projectId: 'savorsip-8c64d',
    storageBucket: 'savorsip-8c64d.appspot.com',
    iosBundleId: 'com.example.savorsip.RunnerTests',
  );
}
